blank_issues_enabled: false
contact_links:
  - name: RMCL 文档反馈
    url: https://github.com/Round-Studio/round-studio.github.io/issues/new
    about: 反馈 RMCL 文档相关问题
  - name: 讨论区
    url: https://github.com/Round-Studio/Round.NET.AvaloniaApp.MinecraftLauncher/discussions/
    about: 使用中若遇到问题或有新点子新需求，请先在这里求助和征求意见。
  - name: 加入 QQ 群
    url: https://qm.qq.com/q/ajSj977gsw
    about: 在 QQ 群和开发者以及其它用户交流讨论。（群号：311568902）
